//https://onlinetexttools.com/convert-text-to-nice-columns <= beautify this array - Right-align columns
// prettier-ignore
export default [
  'wall', 'wall', 'wall', 'wall', 'wall',  'wall',  'wall',  'wall',  'wall', 'wall',  'wall', 'wall', 'wall', 'wall', 'wall',
  'wall',      0,      0, 'jail',      0,       0,       0,       0,       0,      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0, 'wall', 'wall',      0,       0,       0,       0,       0,      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0,      0, 'jail',      0,       0, 'stone', 'stone', 'stone',      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0, 'wall', 'wall',      0,       0,       0,       0, 'stone',      0,  'wall', 'wall', 'wall',      'lamp', 'wood',
  'wall',      0,      0, 'jail',      0,       0,       0,       0, 'stone',      0,       0,      0,      0,      0, 'wood',
  'wall',      0, 'wall', 'wall',      0, 'stone', 'stone', 'stone', 'stone',      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       'table',       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0, 'stone',       0,       0,       0,      0, 'lamp', 'stone', 'wall', 'wall', 'wood',
  'wall',      0,      0,      0,      0, 'stone', 'stone', 'stone', 'stone',      0,       0,      0, 'wall',      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0, 'wall',      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,  'wall', 'wall', 'wall',      0, 'wood',
  'wall',      0,      0,      0, 'wall',  'wall',       0,       0,       0,      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0,      0,      0, 'wall',       0,       0,       0,       0,      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0,      0,      0, 'wall',       0,       0, 'stone',       0,      0,  'wall',      0,      0,      0, 'wood',
  'wall',      0,      0,      0, 'wall',       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      'lamp',       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      'table',       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall', 'wall', 'wall', 'wall', 'wall', 0,  'wall',  'wall',  'wall', 'wall',  'wall', 'wall', 'wall', 'wall', 'wall',
  'wall',      0,      'wall',      0,      0,       0,       0,       0,       'table',      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      'table',      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall',      0,      0,      0,      0,       0,       0,       0,       0,      0,       0,      0,      0,      0, 'wood',
  'wall', 'wood', 'wood', 'wood', 'wood',  'wood',  'wood',  'wood',  'wood', 'wood',  'wood', 'wood', 'wood', 'wood', 'wood',
];
